### ISSUE TITLE
Failure in long-running process mode - spawn C ENOENT

### ISSUE THREAD

**Issue by kendfrey** [foreverjs/forever#1000]
I'm trying to run `forever` with a specific version of node (from nvm-windows).

```
forever -c C:\Users\Kendall\AppData\Roaming\nvm\v9.0.0\node server.js
```

Output:

```
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
events.js:193
      throw er; // Unhandled 'error' event
      ^

Error: spawn C ENOENT
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

No error occurs when I do `forever start -c ...`.

What is wrong?

**Comment by panlina** [comment]
Same here. Seems it's because of some kind of `safetyChecks`:
https://github.com/foreverjs/forever-monitor/blob/771ea2216082bcd168ca5c6ed6c8e8c89304616b/lib/forever-monitor/monitor.js#L469
https://github.com/foreverjs/forever-monitor/blob/771ea2216082bcd168ca5c6ed6c8e8c89304616b/lib/forever-monitor/monitor.js#L498
It requires the command itself quoted, so you have to write `-c """c:\...\node"""`(windows uses double quote to escape a quote).
I don't like the extra layer of interpretation. Can it be done by just giving a command text(including the arguments), where the executable part may be surrounded by quotes as the platform demands when necessary?
```
-c node index.js	//no quotes needed
-c c:\node index.js	//if there's no spaces, quotes are not needed
-c "c:\node -r esm" index.js	//top level quotes are needed to allow spaces in the -c argument
-c """c:\path with spaces\node"" -r esm" index.js	//top level quotes are needed to allow spaces in the -c argument, and secondary level of quotes are needed to allow spaces in the executable part of command text itself
```
The above is for windows. As for other platforms, it will be the corresponding escape mechanism, like using `\"` to escape `"` on Linux.
