### ISSUE TITLE
forever logs not working?!

### ISSUE THREAD

**Issue by jeffrson** [foreverjs/forever#1001]
Hi,

I'm trying to get started with forever. I have this simple script index.js:
```
setInterval(() => console.log('Ping!'), 5000);
```

which is run by `forever start index.js`, can be shown inside `forever list`, could be stopped with `forever stop 0`. However, I cannot see the logs. There is a logfile name shown in `forever list` - the log file exists and is written to, but `forever logs 0` returns this error:

```
>forever logs 0 -f
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn tail ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

**Comment by thanhthang20** [comment]
The same issue
