### ISSUE TITLE
When -w -watchDirectory is specified from command line, throws error 

### ISSUE THREAD

**Issue by acoulon99** [foreverjs/forever#727]
Anyone else having this issue?
I'm starting our server with:
forever start -w -watchDirectory "/home/vagrant/server" -l ./../runtime/logs/server/server.log ./runtime/server/server.js

however I'm getting the error:
fs.js:423
  binding.open(pathModule._makeLong(path),
          ^
TypeError: path must be a string
    at Object.fs.open (fs.js:423:11)
    at WriteStream.open (fs.js:1657:6)
    at new WriteStream (fs.js:1647:10)
    at Object.fs.createWriteStream (fs.js:1611:10)
    at exports.attach (/usr/local/lib/node_modules/forever/node_modules/forever$
    at Object.bootstrap (/usr/local/lib/node_modules/forever/node_modules/forev$
    at exports.App (/usr/local/lib/node_modules/forever/node_modules/forever-mo$
    at new exports.Monitor (/usr/local/lib/node_modules/forever/node_modules/fo$
    at start (/usr/local/lib/node_modules/forever/bin/monitor:23:17)
    at process.<anonymous> (/usr/local/lib/node_modules/forever/bin/monitor:85:$

I've tried supplying the argument raw and as a string but get the same outcome

**Comment by acoulon99** [comment]
/idiotStatus... lol.. forgot the second '-' on the watchDirectory option...
