### ISSUE TITLE
Log files are always being saved to default directory

### ISSUE THREAD

**Issue by franciszabala** [foreverjs/forever#747]
I tried running this command:
```
forever start ./bin/www -l '/logs/nodejs/mylog.log' -o '/logs/nodejs/out.log' -e '/logs/nodejs/error.log' --spinSleepTime 10000 -c
```
But it keeps saving the logs in the default directory. It completely ignores the flags

**Comment by jcollum** [comment]
I'm seeing this too. `-l` seems to be ignored. My command looks like 

```
forever start ./lib/a/dist/start.js ./lib/a/dist/b ./src/start.config.yaml -l /e/logs/a/b/forever.2015.log
```

(The `/e/` is because I'm running this on Windows via git-bash.)

Perhaps the entire command I need to run should be in quotes? That seems odd but I'll try it.

**Comment by jcollum** [comment]
@franciszabala It seems that forever is a bit finicky about placement of command line tokens. Try putting `-l` etc before your script path. Worked for me.

**Comment by franciszabala** [comment]
You mean like this?:

```
forever start ./bin/www -l '/logs/nodejs/mylog.log'
````

**Comment by jcollum** [comment]
Yeah, did that help?

**Comment by franciszabala** [comment]
No, it didn't.

**Comment by prtome** [comment]
Did you solve the problem ? I see the same problem. I tried the -p option, to put all files in one directory

         forever start ./bin/www ./ -p ../forever

I see you put '' are these mandatory? should I put '../forever' The server is perfectly working, all logs into /root/.forever (I start the server as a daemon)
thanks

**Comment by franciszabala** [comment]
Hi, I am not sure how I solved my problem exactly but this is the answer I think this is how I did it:

    FOREVER_ROOT=<PATH-TO-YOUR-LOG> ./node_modules/.bin/forever start -o output.log -e error.log test.js

No need for the apostrophes. Let me know if it worked.

<em>Buy gold buy!</em>

**Comment by jcollum** [comment]
Here's my command line for forever (pipes to bunyan as well, Windows box): 

```
forever -o "E:\logs\sunBear\forever.2015.log" --append "./node_modules/sunBear/dist/start.js" "./node_modules/sunBear/dist/manager.js"  "./src/config.yaml" | bunyan -l trace
```

Maybe it helps.

**Comment by prtome** [comment]
Thank you both for your help.

adding the FOREVER_ROOT worked and all files are where I want them.
I cannot get -o and -e options to work, it still writes its own logs, but it is ok, we are debugging so like this there are smaller logs with the timestamp. I am on Debian7
I can live with that ;)
In your command are the logs overwritten or appended ?

**Comment by thomcom** [comment]
FOREVER_ROOT works for me, though it also creates `pids` and `sock` directories there.  Good enough solution.

**Comment by kiro112** [comment]
Hi, im currently encountering this situation.
```
FOREVER_ROOT=/mylogs forever -o forever.log -e err.log -o out.log start cluster.js
forever list
info:    No forever processes running
```
base on the forever log it say path must be a string or buffer
```
fs.js:632
  binding.open(pathModule._makeLong(path),
          ^

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.open (fs.js:632:11)
    at WriteStream.open (fs.js:2118:6)
    at new WriteStream (fs.js:2104:10)
    at Object.fs.createWriteStream (fs.js:2059:10)
    at exports.attach (/home/codemagnus/.nvm/versions/node/v6.11.0/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/plugins/logger.js:27:43)
    at Object.bootstrap (/home/codemagnus/.nvm/versions/node/v6.11.0/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/monitor.js:34:27)
    at exports.App (/home/codemagnus/.nvm/versions/node/v6.11.0/lib/node_modules/forever/node_modules/broadway/lib/broadway/app.js:47:21)
    at new exports.Monitor (/home/codemagnus/.nvm/versions/node/v6.11.0/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/monitor.js:141:16)
    at start (/home/codemagnus/.nvm/versions/node/v6.11.0/lib/node_modules/forever/bin/monitor:23:17)
```

The folder `/mylogs` already has the permission `drwxrwxrwx`

how do you run it ?

**Comment by sue891206** [comment]
```
You need to add the log destination specifiers before the filename to run. So
forever -e /path/error.txt -o /path/output.txt start index.js
```
**This really works fine in my env!!! ^0^**

see from：https://stackoverflow.com/questions/21021186/where-does-forever-store-console-log-output
