### ISSUE TITLE
Possible memory leak in v0.15.1?

### ISSUE THREAD

**Issue by akobler** [foreverjs/forever#775]
Hi all

First, thanks for the application, helped already a lot to keep node processes running.

I have found a warning about a possible memory leak and the according trace in my forever log file. It seems for me, that the cause is in forever code. If files change, normally I observe the "restarting script because change changed" entry followed by two other lines. Before the warning popped up, the "restarting script because change changed" was reported 10 times in sequence without the other log lines.

I use v.0.15.1 and start the node application as follows:
```
forever -a -l "$logDir/forever.log" -w --watchIgnore "*.pyc" start server.js
```

forever log with warning and trace:
```
error: restarting script because change changed
error: Forever detected script was killed by signal: SIGKILL
error: Script restart attempt #4
error: restarting script because change changed
error: Forever detected script was killed by signal: SIGKILL
error: Script restart attempt #5
error: restarting script because change changed
error: Forever detected script was killed by signal: SIGKILL
error: Script restart attempt #6
error: restarting script because change changed
error: Forever detected script was killed by signal: SIGKILL
error: Script restart attempt #7
error: restarting script because change changed
error: restarting script because change changed
error: restarting script because change changed
error: restarting script because change changed
error: restarting script because change changed
error: restarting script because change changed
error: restarting script because change changed
error: restarting script because change changed
error: restarting script because change changed
error: restarting script because change changed
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ChildProcess.EventEmitter.addListener (events.js:160:15)
    at ChildProcess.EventEmitter.once (events.js:185:8)
    at Monitor.kill (/usr/local/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/monitor.js:381:11)
    at Monitor.restart (/usr/local/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/monitor.js:332:12)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/plugins/watch.js:77:15)
    at EventEmitter.emit (events.js:106:17)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/chokidar/index.js:152:38)
    at EventEmitter.FSWatcher._emit (/usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/chokidar/index.js:179:5)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/chokidar/lib/nodefs-handler.js:263:16)
    at Object.oncomplete (fs.js:107:15)
error: Forever detected script was killed by signal: SIGKILL
error: Script restart attempt #8
error: restarting script because change changed
error: restarting script because change changed
error: restarting script because add changed
error: restarting script because add changed
error: Forever detected script was killed by signal: SIGKILL
error: Script restart attempt #9
error: restarting script because add changed
error: Forever detected script was killed by signal: SIGKILL
error: Script restart attempt #10
error: restarting script because unlink changed
error: Forever detected script was killed by signal: SIGKILL
error: Script restart attempt #11
```

Anybody else observing the same?

Best, Andi

**Comment by jworm7** [comment]
I'm experiencing the same issue. Were you able to resolve the problem?

**Comment by akobler** [comment]
No, haven't yet resolved the problem.

**Comment by zdila** [comment]
Same problem here.

**Comment by zdila** [comment]
`forever` should add an option to delay the restart on file change to prevent many restarts when many files change at once.

**Comment by mikeatlas** [comment]
Hitting this as well now here. Hard to know what changed since I recently moved to a brand new environment and wonder if my local version of foreverjs was different from the one in my last environment.

**Comment by mikeatlas** [comment]
FWIW my forever.js command runs `shelljs` to delay restarts on crashes, but there's no way to delay forever.js restarts themselves on watches (they are treated as two different areas of code base if you dig into the source here).

```javascript
// my-forever-app.js
require('shelljs/global');

setTimeout(function(){
  exec('./my-app', {async:true});
}, 3000);
```

**Comment by huglap** [comment]
If you are using shelljs to start your app and haven't disable the log file output, make sure to add /shelljs* to your .foreverignore file.
