### ISSUE TITLE
ERROR: throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by mato75** [foreverjs/forever#789]
When a file gets changed, I get this error:

> affinity@0.0.1 start /vagrant
> forever -w server/app.js

warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
Example app listening at http://:::3000
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: watch /vagrant/node_modules/gulp-print/node_modules/map-stream/examples ENOSPC
    at exports._errnoException (util.js:856:11)
    at FSWatcher.start (fs.js:1314:19)
    at Object.fs.watch (fs.js:1342:11)
    at createFsWatchInstance (/vagrant/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/vagrant/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/vagrant/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/vagrant/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/vagrant/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/vagrant/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:83:15)

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! affinity@0.0.1 start: `forever -w server/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the affinity@0.0.1 start script 'forever -w server/app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the affinity package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     forever -w server/app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls affinity
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
vagrant@vagrant:/vagrant$

**Comment by mato75** [comment]
The answer: 

http://stackoverflow.com/questions/22475849/node-js-error-enospc
