### ISSUE TITLE
stopAll does not complete execution when child spinning

### ISSUE THREAD

**Issue by semblano** [foreverjs/forever#791]
When a child script is spinning and you issue the command `forever stopall`, it kills the child process but not the forever one.

## How To reproduce ##

Take this basic script that will 'fail' at startup, and will begin *spinning*.

##### *test.js* #####
```javascript
throw new Error("Some error");
```

##### Start it using *forever* #####
```
$ forever --pidFile /path/to/test.pid -a -l /var/log/test.log --minUptime 5000 --spinSleepTime 2000 start -d /path/to/test.js
```
Wait a couple of seconds for it to start spinning.

##### Stop it using the *stopall* command: #####
```
$ forever stopall
```

At this time, the stop command does not return (does not complete it's execution), and no more info is added to the logs:

##### Log Content #####
```
/path/to/test.js:1
(function (exports, require, module, __filename, __dirname) { throw new Error("Some error");
                                                              ^

Error: Some error
    at Object.<anonymous> (/path/to/test.js:1:69)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
error: Forever detected script exited with code: 1
error: Script restart attempt #4
/path/to/test.js:1
(function (exports, require, module, __filename, __dirname) { throw new Error("Some error");
                                                              ^

Error: Some error
    at Object.<anonymous> (/tmp/semblano/test.js:1:69)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
error: Forever detected script exited with code: 1
```
And the forever process is still running:
```
24033 ?        Ssl    0:00 /opt/node-v5.0.0-linux-x64/bin/node /path/to/forever/bin/monitor /path/to/test.js
```

**Comment by pamelazagatti** [comment]
+1

**Comment by renatotrev** [comment]
+1

**Comment by bcandido** [comment]
+1
