### ISSUE TITLE
ERRO START SERVICE 

### ISSUE THREAD

**Issue by arturfrota** [foreverjs/forever#836]
Error starting service FOREVER

When starting status Service and STOPPED

LOG

error: Forever detected script exited with code: 143
error: Script restart attempt #1
error: Forever detected script was killed by signal: SIGKILL
error: Script restart attempt #2

error: Forever detected script was killed by signal: SIGTERM

**Comment by arturfrota** [comment]
error: Could not read .foreverignore file. 
error: ENOENT, open '/var/www/html/a/whatsapp/run/ws/.foreverignore'
   
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at net.js:1143:9
    at dns.js:72:18
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:902:3
error: Forever detected script exited with code: 8

**Comment by arturfrota** [comment]
error: Could not read .foreverignore file. 
error: ENOENT, open 
   
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at net.js:1143:9
    at dns.js:72:18
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:902:3
error: Forever detected script exited with code: 8
