### ISSUE TITLE
How to only output forever logs and err logs?

### ISSUE THREAD

**Issue by LunaticoCR** [foreverjs/forever#872]
Hello,

I'm new to using forever, I want to use it on a production server. On our server we use bunyan for logging and we already write the server logs on separate files, so the output form stdout is redundant.
I've been playing around with the different options of forever to see if I can get it to only print forever logs and stderr logs, either to the same or different files. But I have not found a way of doing this.

Is this possible?

Thank you!

**Comment by LunaticoCR** [comment]
Ok found a combination that sort-of works...

`cd ~/path/to/server/ && forever start --uid "server" --watch --watchDirectory $PWD --append --debug --verbose -e logs/forever_error.log --silent server_test.js`

So this is logging stderr to logs/forever_error.log but the forever logs are still on ~/.forever/server.log, I'd like to move this to the same logs directory if possible.

If I add `-o logs/forever.log` it's also adding stdout with the server logs. If I add `-l logs/forever.log` it crashes with error:
```
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: server_test.js
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/user/.forever/logs/forever.log'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.forever.startDaemon (/usr/local/lib/node_modules/forever/lib/forever.js:460:14)
    at /usr/local/lib/node_modules/forever/lib/forever/cli.js:319:15
    at /usr/local/lib/node_modules/forever/lib/forever/cli.js:162:5
    at /usr/local/lib/node_modules/forever/lib/forever.js:409:24
    at FSReqWrap.oncomplete (fs.js:82:15)

```

**Comment by LunaticoCR** [comment]
Figured it, using:

`cd ~/path/to/server/ && forever start --uid "server" --minUptime 1000 --spinSleepTime 1000 --watch --watchDirectory $PWD --append --debug --verbose -l $PWD/logs/forever.log -e $PWD/logs/forever_error.log --silent server_test.js`
