### ISSUE TITLE
Forever not restarting if process.exit(1)

### ISSUE THREAD

**Issue by mercmobily** [foreverjs/forever#908]
I am running forever with the following command:

    forever start -a $EXTRA_SWITCH -l /var/log/forever/forever.log -o /var/log/forever/out.log -e /var/log/forever/err.log  server.js

In my server, I have:

    mongodb.MongoClient.connect( mongoUrl, {
      bufferMaxEntries: 0,
      reconnectTries: -1,
    }, function( err, db ){

      // The connection is 100% necessary
      if( err ){
        console.error( "Could not connect to the database. Aborting. Error:", err );
        process.exit(1);
      }

The database server is down on purpose. The idea is that this script might be launched before the db server is actually up, with forever retrying to launch the script.

In the logs, I am getting:

    Could not connect to the database. Aborting. Error: { Error: connect ECONNREFUSED 127.0.0.1:27017
        at Object.exports._errnoException (util.js:1022:11)
        at exports._exceptionWithHostPort (util.js:1045:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
      name: 'MongoError',
      message: 'connect ECONNREFUSED 127.0.0.1:27017' }
    error: Forever detected script exited with code: 1

But, `forever` doesn't seem to want to re-run the script.
Running it, the process is STOPPED:

    [forever@centos755208 ~]$ forever list
    info:    Forever processes running
    data:        uid  command       script    forever pid  id logfile                                               uptime  
    data:    [0] j_ul /usr/bin/node server.js 4658    4668    /var/log/forever/forever.log STOPPED 
    [forever@centos755208 ~]$ 

Does forever not restart processes that have `process.exit()`ed on their own?

**Comment by ashishjain3456** [comment]
Hello @mercmobily , 
Did you found any stable solution for above issue?
We are facing similar issue.

**Comment by mercmobily** [comment]
In my case, it happened because my process died too quickly. When that happens, forever stops restarting altogether.
I would avoid using forever unless somebody steps up and starts maintaining it for real.

https://github.com/foreverjs/forever/issues/920
